// generated by stringer -type=State; DO NOT EDIT

package pool

import "fmt"

const _State_name = "UNAVAILABLEREAD_ONLYREAD_WRITE"

var _State_index = [...]uint8{0, 11, 20, 30}

func (i State) String() string {
	if i < 0 || i+1 >= State(len(_State_index)) {
		return fmt.Sprintf("State(%d)", i)
	}
	return _State_name[_State_index[i]:_State_index[i+1]]
}
